// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity_log.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createActivityLog = `-- name: CreateActivityLog :one
INSERT INTO activity_log (
    user_id, run_day_id, date, run_type,
    distance, duration, pace, rpe, notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, user_id, run_day_id, date, run_type, distance, duration, pace, rpe, notes, logged_at
`

type CreateActivityLogParams struct {
	UserID   int32         `json:"user_id"`
	RunDayID pgtype.Int4   `json:"run_day_id"`
	Date     pgtype.Date   `json:"date"`
	RunType  string        `json:"run_type"`
	Distance pgtype.Float8 `json:"distance"`
	Duration pgtype.Int4   `json:"duration"`
	Pace     pgtype.Int4   `json:"pace"`
	Rpe      pgtype.Int2   `json:"rpe"`
	Notes    pgtype.Text   `json:"notes"`
}

func (q *Queries) CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (ActivityLog, error) {
	row := q.db.QueryRow(ctx, createActivityLog,
		arg.UserID,
		arg.RunDayID,
		arg.Date,
		arg.RunType,
		arg.Distance,
		arg.Duration,
		arg.Pace,
		arg.Rpe,
		arg.Notes,
	)
	var i ActivityLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RunDayID,
		&i.Date,
		&i.RunType,
		&i.Distance,
		&i.Duration,
		&i.Pace,
		&i.Rpe,
		&i.Notes,
		&i.LoggedAt,
	)
	return i, err
}

const deleteActivityLog = `-- name: DeleteActivityLog :exec
DELETE FROM activity_log WHERE id = $1
`

func (q *Queries) DeleteActivityLog(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteActivityLog, id)
	return err
}

const getActivityLogByID = `-- name: GetActivityLogByID :one
SELECT id, user_id, run_day_id, date, run_type, distance, duration, pace, rpe, notes, logged_at FROM activity_log
WHERE id = $1
`

func (q *Queries) GetActivityLogByID(ctx context.Context, id int32) (ActivityLog, error) {
	row := q.db.QueryRow(ctx, getActivityLogByID, id)
	var i ActivityLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RunDayID,
		&i.Date,
		&i.RunType,
		&i.Distance,
		&i.Duration,
		&i.Pace,
		&i.Rpe,
		&i.Notes,
		&i.LoggedAt,
	)
	return i, err
}

const getActivityLogByRunDay = `-- name: GetActivityLogByRunDay :one
SELECT id, user_id, run_day_id, date, run_type, distance, duration, pace, rpe, notes, logged_at FROM activity_log
WHERE run_day_id = $1
LIMIT 1
`

func (q *Queries) GetActivityLogByRunDay(ctx context.Context, runDayID pgtype.Int4) (ActivityLog, error) {
	row := q.db.QueryRow(ctx, getActivityLogByRunDay, runDayID)
	var i ActivityLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RunDayID,
		&i.Date,
		&i.RunType,
		&i.Distance,
		&i.Duration,
		&i.Pace,
		&i.Rpe,
		&i.Notes,
		&i.LoggedAt,
	)
	return i, err
}

const getActivitySummaryByUser = `-- name: GetActivitySummaryByUser :one
SELECT
    COUNT(*)                          AS total_runs,
    COALESCE(SUM(distance), 0)        AS total_distance,
    COALESCE(SUM(duration), 0)        AS total_duration,
    COALESCE(AVG(rpe), 0)             AS avg_rpe,
    COALESCE(AVG(distance), 0)        AS avg_distance
FROM activity_log
WHERE user_id = $1
AND date >= CURRENT_DATE - INTERVAL '30 days'
`

type GetActivitySummaryByUserRow struct {
	TotalRuns     int64       `json:"total_runs"`
	TotalDistance interface{} `json:"total_distance"`
	TotalDuration interface{} `json:"total_duration"`
	AvgRpe        interface{} `json:"avg_rpe"`
	AvgDistance   interface{} `json:"avg_distance"`
}

func (q *Queries) GetActivitySummaryByUser(ctx context.Context, userID int32) (GetActivitySummaryByUserRow, error) {
	row := q.db.QueryRow(ctx, getActivitySummaryByUser, userID)
	var i GetActivitySummaryByUserRow
	err := row.Scan(
		&i.TotalRuns,
		&i.TotalDistance,
		&i.TotalDuration,
		&i.AvgRpe,
		&i.AvgDistance,
	)
	return i, err
}

const getRecentActivityByUser = `-- name: GetRecentActivityByUser :many
SELECT id, user_id, run_day_id, date, run_type, distance, duration, pace, rpe, notes, logged_at FROM activity_log
WHERE user_id = $1
AND date >= CURRENT_DATE - INTERVAL '30 days'
ORDER BY date DESC
`

func (q *Queries) GetRecentActivityByUser(ctx context.Context, userID int32) ([]ActivityLog, error) {
	rows, err := q.db.Query(ctx, getRecentActivityByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityLog
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RunDayID,
			&i.Date,
			&i.RunType,
			&i.Distance,
			&i.Duration,
			&i.Pace,
			&i.Rpe,
			&i.Notes,
			&i.LoggedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityLogByUser = `-- name: ListActivityLogByUser :many
SELECT id, user_id, run_day_id, date, run_type, distance, duration, pace, rpe, notes, logged_at FROM activity_log
WHERE user_id = $1
ORDER BY date DESC
`

func (q *Queries) ListActivityLogByUser(ctx context.Context, userID int32) ([]ActivityLog, error) {
	rows, err := q.db.Query(ctx, listActivityLogByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityLog
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RunDayID,
			&i.Date,
			&i.RunType,
			&i.Distance,
			&i.Duration,
			&i.Pace,
			&i.Rpe,
			&i.Notes,
			&i.LoggedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityLogByUserPaged = `-- name: ListActivityLogByUserPaged :many
SELECT id, user_id, run_day_id, date, run_type, distance, duration, pace, rpe, notes, logged_at FROM activity_log
WHERE user_id = $1
ORDER BY date DESC
LIMIT $2 OFFSET $3
`

type ListActivityLogByUserPagedParams struct {
	UserID int32 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListActivityLogByUserPaged(ctx context.Context, arg ListActivityLogByUserPagedParams) ([]ActivityLog, error) {
	rows, err := q.db.Query(ctx, listActivityLogByUserPaged, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityLog
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RunDayID,
			&i.Date,
			&i.RunType,
			&i.Distance,
			&i.Duration,
			&i.Pace,
			&i.Rpe,
			&i.Notes,
			&i.LoggedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateActivityLog = `-- name: UpdateActivityLog :one
UPDATE activity_log
SET distance = $2,
    duration = $3,
    pace     = $4,
    rpe      = $5,
    notes    = $6
WHERE id = $1
RETURNING id, user_id, run_day_id, date, run_type, distance, duration, pace, rpe, notes, logged_at
`

type UpdateActivityLogParams struct {
	ID       int32         `json:"id"`
	Distance pgtype.Float8 `json:"distance"`
	Duration pgtype.Int4   `json:"duration"`
	Pace     pgtype.Int4   `json:"pace"`
	Rpe      pgtype.Int2   `json:"rpe"`
	Notes    pgtype.Text   `json:"notes"`
}

func (q *Queries) UpdateActivityLog(ctx context.Context, arg UpdateActivityLogParams) (ActivityLog, error) {
	row := q.db.QueryRow(ctx, updateActivityLog,
		arg.ID,
		arg.Distance,
		arg.Duration,
		arg.Pace,
		arg.Rpe,
		arg.Notes,
	)
	var i ActivityLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RunDayID,
		&i.Date,
		&i.RunType,
		&i.Distance,
		&i.Duration,
		&i.Pace,
		&i.Rpe,
		&i.Notes,
		&i.LoggedAt,
	)
	return i, err
}
