// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hr_history.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getHRHistoryByUser = `-- name: GetHRHistoryByUser :many
SELECT id, user_id, max_hr, resting_hr, lthr, method, recorded_at FROM user_hr_history
WHERE user_id = $1
ORDER BY recorded_at DESC
LIMIT 10
`

func (q *Queries) GetHRHistoryByUser(ctx context.Context, userID int32) ([]UserHrHistory, error) {
	rows, err := q.db.Query(ctx, getHRHistoryByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserHrHistory
	for rows.Next() {
		var i UserHrHistory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MaxHr,
			&i.RestingHr,
			&i.Lthr,
			&i.Method,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertHRHistory = `-- name: InsertHRHistory :exec
INSERT INTO user_hr_history (user_id, max_hr, resting_hr, lthr, method)
VALUES ($1, $2, $3, $4, $5)
`

type InsertHRHistoryParams struct {
	UserID    int32       `json:"user_id"`
	MaxHr     pgtype.Int4 `json:"max_hr"`
	RestingHr pgtype.Int4 `json:"resting_hr"`
	Lthr      pgtype.Int4 `json:"lthr"`
	Method    string      `json:"method"`
}

func (q *Queries) InsertHRHistory(ctx context.Context, arg InsertHRHistoryParams) error {
	_, err := q.db.Exec(ctx, insertHRHistory,
		arg.UserID,
		arg.MaxHr,
		arg.RestingHr,
		arg.Lthr,
		arg.Method,
	)
	return err
}
