// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hr_profiles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHRProfile = `-- name: CreateHRProfile :one
INSERT INTO user_hr_profile (user_id, max_hr, resting_hr, lactate_threshold_hr, calculation_method)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, max_hr, resting_hr, lactate_threshold_hr, calculation_method, created_at
`

type CreateHRProfileParams struct {
	UserID             int32       `json:"user_id"`
	MaxHr              pgtype.Int4 `json:"max_hr"`
	RestingHr          pgtype.Int4 `json:"resting_hr"`
	LactateThresholdHr pgtype.Int4 `json:"lactate_threshold_hr"`
	CalculationMethod  string      `json:"calculation_method"`
}

func (q *Queries) CreateHRProfile(ctx context.Context, arg CreateHRProfileParams) (UserHrProfile, error) {
	row := q.db.QueryRow(ctx, createHRProfile,
		arg.UserID,
		arg.MaxHr,
		arg.RestingHr,
		arg.LactateThresholdHr,
		arg.CalculationMethod,
	)
	var i UserHrProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MaxHr,
		&i.RestingHr,
		&i.LactateThresholdHr,
		&i.CalculationMethod,
		&i.CreatedAt,
	)
	return i, err
}

const getHRProfileByUser = `-- name: GetHRProfileByUser :one
SELECT id, user_id, max_hr, resting_hr, lactate_threshold_hr, calculation_method, created_at FROM user_hr_profile
WHERE user_id = $1
`

func (q *Queries) GetHRProfileByUser(ctx context.Context, userID int32) (UserHrProfile, error) {
	row := q.db.QueryRow(ctx, getHRProfileByUser, userID)
	var i UserHrProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MaxHr,
		&i.RestingHr,
		&i.LactateThresholdHr,
		&i.CalculationMethod,
		&i.CreatedAt,
	)
	return i, err
}

const updateHRProfile = `-- name: UpdateHRProfile :one
UPDATE user_hr_profile
SET max_hr = $2,
    resting_hr = $3,
    lactate_threshold_hr = $4,
    calculation_method = $5
WHERE user_id = $1
RETURNING id, user_id, max_hr, resting_hr, lactate_threshold_hr, calculation_method, created_at
`

type UpdateHRProfileParams struct {
	UserID             int32       `json:"user_id"`
	MaxHr              pgtype.Int4 `json:"max_hr"`
	RestingHr          pgtype.Int4 `json:"resting_hr"`
	LactateThresholdHr pgtype.Int4 `json:"lactate_threshold_hr"`
	CalculationMethod  string      `json:"calculation_method"`
}

func (q *Queries) UpdateHRProfile(ctx context.Context, arg UpdateHRProfileParams) (UserHrProfile, error) {
	row := q.db.QueryRow(ctx, updateHRProfile,
		arg.UserID,
		arg.MaxHr,
		arg.RestingHr,
		arg.LactateThresholdHr,
		arg.CalculationMethod,
	)
	var i UserHrProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MaxHr,
		&i.RestingHr,
		&i.LactateThresholdHr,
		&i.CalculationMethod,
		&i.CreatedAt,
	)
	return i, err
}
