// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type HrZone struct {
	ID          int32            `json:"id"`
	ProfileID   int32            `json:"profile_id"`
	ZoneNumber  int32            `json:"zone_number"`
	Name        pgtype.Text      `json:"name"`
	HrMin       int32            `json:"hr_min"`
	HrMax       int32            `json:"hr_max"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type RunDay struct {
	ID            int32            `json:"id"`
	PlanID        int32            `json:"plan_id"`
	Date          pgtype.Date      `json:"date"`
	RunType       string           `json:"run_type"`
	TotalDistance pgtype.Float8    `json:"total_distance"`
	TotalDuration pgtype.Int8      `json:"total_duration"`
	Completed     bool             `json:"completed"`
	Notes         pgtype.Text      `json:"notes"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

type Segment struct {
	ID             int32            `json:"id"`
	RunID          int32            `json:"run_id"`
	OrderIndex     int32            `json:"order_index"`
	Description    pgtype.Text      `json:"description"`
	EffortType     string           `json:"effort_type"`
	Duration       pgtype.Int8      `json:"duration"`
	Distance       pgtype.Float8    `json:"distance"`
	Pace           pgtype.Int8      `json:"pace"`
	Repetitions    int32            `json:"repetitions"`
	HrZoneMin      pgtype.Int4      `json:"hr_zone_min"`
	HrZoneMax      pgtype.Int4      `json:"hr_zone_max"`
	HrAbsMin       pgtype.Int4      `json:"hr_abs_min"`
	HrAbsMax       pgtype.Int4      `json:"hr_abs_max"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	SetIndex       pgtype.Int4      `json:"set_index"`
	SetRepetitions pgtype.Int4      `json:"set_repetitions"`
}

type TemplatePlan struct {
	ID                int32            `json:"id"`
	Name              string           `json:"name"`
	Description       pgtype.Text      `json:"description"`
	PlanType          string           `json:"plan_type"`
	DistanceUnit      string           `json:"distance_unit"`
	TotalWeeks        int32            `json:"total_weeks"`
	PeakWeeklyMileage pgtype.Numeric   `json:"peak_weekly_mileage"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
}

type TemplateRunDay struct {
	ID        int32            `json:"id"`
	PlanID    int32            `json:"plan_id"`
	DayOffset int32            `json:"day_offset"`
	RunType   string           `json:"run_type"`
	Distance  pgtype.Float8    `json:"distance"`
	Notes     pgtype.Text      `json:"notes"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type TemplateSegment struct {
	ID             int32            `json:"id"`
	RunID          int32            `json:"run_id"`
	OrderIndex     int32            `json:"order_index"`
	Description    pgtype.Text      `json:"description"`
	EffortType     string           `json:"effort_type"`
	Distance       pgtype.Float8    `json:"distance"`
	Duration       pgtype.Int8      `json:"duration"`
	Pace           pgtype.Int8      `json:"pace"`
	Repetitions    int32            `json:"repetitions"`
	HrZoneMin      pgtype.Int4      `json:"hr_zone_min"`
	HrZoneMax      pgtype.Int4      `json:"hr_zone_max"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	SetIndex       pgtype.Int4      `json:"set_index"`
	SetRepetitions pgtype.Int4      `json:"set_repetitions"`
}

type TrainingPlan struct {
	ID           int32            `json:"id"`
	UserID       int32            `json:"user_id"`
	Name         string           `json:"name"`
	Description  pgtype.Text      `json:"description"`
	PlanType     string           `json:"plan_type"`
	DistanceUnit string           `json:"distance_unit"`
	StartDate    pgtype.Date      `json:"start_date"`
	EndDate      pgtype.Date      `json:"end_date"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	TemplateID   pgtype.Int4      `json:"template_id"`
}

type User struct {
	ID           int32            `json:"id"`
	Email        string           `json:"email"`
	Username     string           `json:"username"`
	PasswordHash string           `json:"password_hash"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type UserHrProfile struct {
	ID                 int32            `json:"id"`
	UserID             int32            `json:"user_id"`
	MaxHr              pgtype.Int4      `json:"max_hr"`
	RestingHr          pgtype.Int4      `json:"resting_hr"`
	LactateThresholdHr pgtype.Int4      `json:"lactate_threshold_hr"`
	CalculationMethod  string           `json:"calculation_method"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
}
