// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateHRProfile(ctx context.Context, arg CreateHRProfileParams) (UserHrProfile, error)
	CreateHRZone(ctx context.Context, arg CreateHRZoneParams) (HrZone, error)
	CreateRunDay(ctx context.Context, arg CreateRunDayParams) (RunDay, error)
	CreateSegment(ctx context.Context, arg CreateSegmentParams) (Segment, error)
	CreateTemplatePlan(ctx context.Context, arg CreateTemplatePlanParams) (TemplatePlan, error)
	CreateTemplateRunDay(ctx context.Context, arg CreateTemplateRunDayParams) (TemplateRunDay, error)
	CreateTemplateSegment(ctx context.Context, arg CreateTemplateSegmentParams) (TemplateSegment, error)
	CreateTrainingPlan(ctx context.Context, arg CreateTrainingPlanParams) (TrainingPlan, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteHRZonesByProfile(ctx context.Context, profileID int32) error
	DeleteRunDay(ctx context.Context, id int32) error
	DeleteRunDayIfOwner(ctx context.Context, arg DeleteRunDayIfOwnerParams) error
	DeleteTrainingPlan(ctx context.Context, id int32) error
	DeleteTrainingPlanIfOwner(ctx context.Context, arg DeleteTrainingPlanIfOwnerParams) error
	DeleteUser(ctx context.Context, id int32) error
	GetHRProfileByUser(ctx context.Context, userID int32) (UserHrProfile, error)
	GetHRZonesByProfile(ctx context.Context, profileID int32) ([]HrZone, error)
	GetHRZonesByUser(ctx context.Context, userID int32) ([]HrZone, error)
	GetRunDay(ctx context.Context, id int32) (RunDay, error)
	GetRunDayWithPlanOwner(ctx context.Context, id int32) (GetRunDayWithPlanOwnerRow, error)
	GetTemplatePlan(ctx context.Context, id int32) (TemplatePlan, error)
	GetTrainingPlan(ctx context.Context, id int32) (TrainingPlan, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListRunDaysByPlan(ctx context.Context, planID int32) ([]RunDay, error)
	ListSegmentsByRun(ctx context.Context, runID int32) ([]Segment, error)
	ListTemplatePlans(ctx context.Context) ([]TemplatePlan, error)
	ListTemplatePlansWithCounts(ctx context.Context) ([]ListTemplatePlansWithCountsRow, error)
	ListTemplateRunDaysByPlan(ctx context.Context, planID int32) ([]TemplateRunDay, error)
	ListTemplateSegmentsByRun(ctx context.Context, runID int32) ([]TemplateSegment, error)
	ListTrainingPlansByUser(ctx context.Context, userID int32) ([]TrainingPlan, error)
	UpdateEmail(ctx context.Context, arg UpdateEmailParams) (User, error)
	UpdateHRProfile(ctx context.Context, arg UpdateHRProfileParams) (UserHrProfile, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdateTrainingPlan(ctx context.Context, arg UpdateTrainingPlanParams) (TrainingPlan, error)
	UpdateUsername(ctx context.Context, arg UpdateUsernameParams) (User, error)
}

var _ Querier = (*Queries)(nil)
