// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateTrainingPlan(ctx context.Context, arg CreateTrainingPlanParams) (TrainingPlan, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteTrainingPlan(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	GetTrainingPlan(ctx context.Context, id int32) (TrainingPlan, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListTrainingPlansByUser(ctx context.Context, userID int32) ([]TrainingPlan, error)
}

var _ Querier = (*Queries)(nil)
