// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: template_segments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTemplateSegment = `-- name: CreateTemplateSegment :one
INSERT INTO template_segments (run_id, order_index, description, effort_type, distance, duration, pace, repetitions, hr_zone_min, hr_zone_max)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, run_id, order_index, description, effort_type, distance, duration, pace, repetitions, hr_zone_min, hr_zone_max, created_at
`

type CreateTemplateSegmentParams struct {
	RunID       int32         `json:"run_id"`
	OrderIndex  int32         `json:"order_index"`
	Description pgtype.Text   `json:"description"`
	EffortType  string        `json:"effort_type"`
	Distance    pgtype.Float8 `json:"distance"`
	Duration    pgtype.Int8   `json:"duration"`
	Pace        pgtype.Int8   `json:"pace"`
	Repetitions int32         `json:"repetitions"`
	HrZoneMin   pgtype.Int4   `json:"hr_zone_min"`
	HrZoneMax   pgtype.Int4   `json:"hr_zone_max"`
}

func (q *Queries) CreateTemplateSegment(ctx context.Context, arg CreateTemplateSegmentParams) (TemplateSegment, error) {
	row := q.db.QueryRow(ctx, createTemplateSegment,
		arg.RunID,
		arg.OrderIndex,
		arg.Description,
		arg.EffortType,
		arg.Distance,
		arg.Duration,
		arg.Pace,
		arg.Repetitions,
		arg.HrZoneMin,
		arg.HrZoneMax,
	)
	var i TemplateSegment
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.OrderIndex,
		&i.Description,
		&i.EffortType,
		&i.Distance,
		&i.Duration,
		&i.Pace,
		&i.Repetitions,
		&i.HrZoneMin,
		&i.HrZoneMax,
		&i.CreatedAt,
	)
	return i, err
}

const listTemplateSegmentsByRun = `-- name: ListTemplateSegmentsByRun :many
SELECT id, run_id, order_index, description, effort_type, distance, duration, pace, repetitions, hr_zone_min, hr_zone_max, created_at FROM template_segments
WHERE run_id = $1
ORDER BY order_index ASC
`

func (q *Queries) ListTemplateSegmentsByRun(ctx context.Context, runID int32) ([]TemplateSegment, error) {
	rows, err := q.db.Query(ctx, listTemplateSegmentsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TemplateSegment
	for rows.Next() {
		var i TemplateSegment
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.OrderIndex,
			&i.Description,
			&i.EffortType,
			&i.Distance,
			&i.Duration,
			&i.Pace,
			&i.Repetitions,
			&i.HrZoneMin,
			&i.HrZoneMax,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
