// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: template_plans.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTemplatePlan = `-- name: CreateTemplatePlan :one
INSERT INTO template_plans (name, description, plan_type, distance_unit, total_weeks, peak_weekly_mileage)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, description, plan_type, distance_unit, total_weeks, peak_weekly_mileage, created_at
`

type CreateTemplatePlanParams struct {
	Name              string         `json:"name"`
	Description       pgtype.Text    `json:"description"`
	PlanType          string         `json:"plan_type"`
	DistanceUnit      string         `json:"distance_unit"`
	TotalWeeks        int32          `json:"total_weeks"`
	PeakWeeklyMileage pgtype.Numeric `json:"peak_weekly_mileage"`
}

func (q *Queries) CreateTemplatePlan(ctx context.Context, arg CreateTemplatePlanParams) (TemplatePlan, error) {
	row := q.db.QueryRow(ctx, createTemplatePlan,
		arg.Name,
		arg.Description,
		arg.PlanType,
		arg.DistanceUnit,
		arg.TotalWeeks,
		arg.PeakWeeklyMileage,
	)
	var i TemplatePlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PlanType,
		&i.DistanceUnit,
		&i.TotalWeeks,
		&i.PeakWeeklyMileage,
		&i.CreatedAt,
	)
	return i, err
}

const getTemplatePlan = `-- name: GetTemplatePlan :one
SELECT id, name, description, plan_type, distance_unit, total_weeks, peak_weekly_mileage, created_at FROM template_plans
WHERE id = $1
`

func (q *Queries) GetTemplatePlan(ctx context.Context, id int32) (TemplatePlan, error) {
	row := q.db.QueryRow(ctx, getTemplatePlan, id)
	var i TemplatePlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PlanType,
		&i.DistanceUnit,
		&i.TotalWeeks,
		&i.PeakWeeklyMileage,
		&i.CreatedAt,
	)
	return i, err
}

const listTemplatePlans = `-- name: ListTemplatePlans :many
SELECT id, name, description, plan_type, distance_unit, total_weeks, peak_weekly_mileage, created_at FROM template_plans
ORDER BY plan_type, total_weeks ASC
`

func (q *Queries) ListTemplatePlans(ctx context.Context) ([]TemplatePlan, error) {
	rows, err := q.db.Query(ctx, listTemplatePlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TemplatePlan
	for rows.Next() {
		var i TemplatePlan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PlanType,
			&i.DistanceUnit,
			&i.TotalWeeks,
			&i.PeakWeeklyMileage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplatePlansWithCounts = `-- name: ListTemplatePlansWithCounts :many
SELECT
    t.id, t.name, t.description, t.plan_type, t.distance_unit, t.total_weeks, t.peak_weekly_mileage, t.created_at,
    COUNT(r.id) AS run_count
FROM template_plans t
LEFT JOIN template_run_days r ON r.plan_id = t.id
GROUP BY t.id
ORDER BY t.plan_type, t.total_weeks ASC
`

type ListTemplatePlansWithCountsRow struct {
	ID                int32            `json:"id"`
	Name              string           `json:"name"`
	Description       pgtype.Text      `json:"description"`
	PlanType          string           `json:"plan_type"`
	DistanceUnit      string           `json:"distance_unit"`
	TotalWeeks        int32            `json:"total_weeks"`
	PeakWeeklyMileage pgtype.Numeric   `json:"peak_weekly_mileage"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	RunCount          int64            `json:"run_count"`
}

func (q *Queries) ListTemplatePlansWithCounts(ctx context.Context) ([]ListTemplatePlansWithCountsRow, error) {
	rows, err := q.db.Query(ctx, listTemplatePlansWithCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTemplatePlansWithCountsRow
	for rows.Next() {
		var i ListTemplatePlansWithCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PlanType,
			&i.DistanceUnit,
			&i.TotalWeeks,
			&i.PeakWeeklyMileage,
			&i.CreatedAt,
			&i.RunCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
