// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: training_plans.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTrainingPlan = `-- name: CreateTrainingPlan :one
INSERT INTO training_plans (user_id, name, description, plan_type, distance_unit, start_date, end_date, template_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, name, description, plan_type, distance_unit, start_date, end_date, created_at, template_id
`

type CreateTrainingPlanParams struct {
	UserID       int32       `json:"user_id"`
	Name         string      `json:"name"`
	Description  pgtype.Text `json:"description"`
	PlanType     string      `json:"plan_type"`
	DistanceUnit string      `json:"distance_unit"`
	StartDate    pgtype.Date `json:"start_date"`
	EndDate      pgtype.Date `json:"end_date"`
	TemplateID   pgtype.Int4 `json:"template_id"`
}

func (q *Queries) CreateTrainingPlan(ctx context.Context, arg CreateTrainingPlanParams) (TrainingPlan, error) {
	row := q.db.QueryRow(ctx, createTrainingPlan,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.PlanType,
		arg.DistanceUnit,
		arg.StartDate,
		arg.EndDate,
		arg.TemplateID,
	)
	var i TrainingPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.PlanType,
		&i.DistanceUnit,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.TemplateID,
	)
	return i, err
}

const deleteTrainingPlan = `-- name: DeleteTrainingPlan :exec
DELETE FROM training_plans WHERE id = $1
`

func (q *Queries) DeleteTrainingPlan(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteTrainingPlan, id)
	return err
}

const deleteTrainingPlanIfOwner = `-- name: DeleteTrainingPlanIfOwner :exec
DELETE FROM training_plans
WHERE id = $1
AND user_id = $2
`

type DeleteTrainingPlanIfOwnerParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteTrainingPlanIfOwner(ctx context.Context, arg DeleteTrainingPlanIfOwnerParams) error {
	_, err := q.db.Exec(ctx, deleteTrainingPlanIfOwner, arg.ID, arg.UserID)
	return err
}

const getTrainingPlan = `-- name: GetTrainingPlan :one
SELECT id, user_id, name, description, plan_type, distance_unit, start_date, end_date, created_at, template_id FROM training_plans WHERE id = $1
`

func (q *Queries) GetTrainingPlan(ctx context.Context, id int32) (TrainingPlan, error) {
	row := q.db.QueryRow(ctx, getTrainingPlan, id)
	var i TrainingPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.PlanType,
		&i.DistanceUnit,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.TemplateID,
	)
	return i, err
}

const listTrainingPlansByUser = `-- name: ListTrainingPlansByUser :many
SELECT id, user_id, name, description, plan_type, distance_unit, start_date, end_date, created_at, template_id FROM training_plans WHERE user_id = $1
`

func (q *Queries) ListTrainingPlansByUser(ctx context.Context, userID int32) ([]TrainingPlan, error) {
	rows, err := q.db.Query(ctx, listTrainingPlansByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrainingPlan
	for rows.Next() {
		var i TrainingPlan
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.PlanType,
			&i.DistanceUnit,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.TemplateID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTrainingPlan = `-- name: UpdateTrainingPlan :one
UPDATE training_plans
SET name = $2, description = $3, plan_type = $4, distance_unit = $5, start_date = $6, end_date = $7, template_id = $8
WHERE id = $1
RETURNING id, user_id, name, description, plan_type, distance_unit, start_date, end_date, created_at, template_id
`

type UpdateTrainingPlanParams struct {
	ID           int32       `json:"id"`
	Name         string      `json:"name"`
	Description  pgtype.Text `json:"description"`
	PlanType     string      `json:"plan_type"`
	DistanceUnit string      `json:"distance_unit"`
	StartDate    pgtype.Date `json:"start_date"`
	EndDate      pgtype.Date `json:"end_date"`
	TemplateID   pgtype.Int4 `json:"template_id"`
}

func (q *Queries) UpdateTrainingPlan(ctx context.Context, arg UpdateTrainingPlanParams) (TrainingPlan, error) {
	row := q.db.QueryRow(ctx, updateTrainingPlan,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.PlanType,
		arg.DistanceUnit,
		arg.StartDate,
		arg.EndDate,
		arg.TemplateID,
	)
	var i TrainingPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.PlanType,
		&i.DistanceUnit,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.TemplateID,
	)
	return i, err
}
